apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app-as
  labels:
    app: netflix-app-as
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app-as
  template:
    metadata:
      labels:
        app: netflix-app-as
    spec:
      containers:
      - name: netflix-app-as
        image: sahaiankit10/netflix:v2
        ports:
        - containerPort: 80
