apiVersion: v1
kind: Service
metadata:
  name: netflix-app-as
  labels:
    app: netflix-app-as
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: netflix-app-as
